- name: Template settings.json
  ansible.builtin.template:
    src: settings.json.j2
    dest: "{{ settings_path }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'