- name: Ansible VS Code Extension by Red Hat
  ansible.builtin.shell: code --install-extension redhat.ansible
  args:
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.vscode/extensions/redhat.ansible-*"


- name: Ansible Extensions (loop)
  ansible.builtin.shell: "code --install-extension {{item}}"
  args:
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.vscode/extensions/{{item}}-*"
  loop:
  - redhat.ansible
  - ms-python.python

- include_tasks: "{{ ansible_os_family }}/{{ ansible_distribution }}/main.yml"
