# old. snapcraft
# - include_tasks: "Debian/.fn/default.yml"

# from: https://code.visualstudio.com/download

- name: Download .deb package
  ansible.builtin.get_url:
    url: "{{debian_download_url}}"
    dest: "{{ download_dir }}/code.deb"
    mode: '0744'

- name: Install .deb package
  ansible.builtin.apt:
    deb: "{{ download_dir }}/code.deb"
  become: true
