---
- hosts: localhost
  roles:
  - dev/ansible-role-Visual-Studio-Code
  - dev/ansible-role-VSCode-Setting
  - dev/ansible-role-VSCode-Extension
#  - UniInc.Visual-Studio-Code
  # - VSCode Setting/Autosave
  # - VSCode Extension

# when open source only:
# - dev/ansible-role-VS-Codium
